
import React from "react";
import { jsPDF } from "jspdf";
import {
  Chart,
  ArcElement,
  BarElement,
  CategoryScale,
  LinearScale,
  Tooltip,
  Legend,
} from "chart.js";

Chart.register(ArcElement, BarElement, CategoryScale, LinearScale, Tooltip, Legend);

export default function ReportPDF() {
  const generatePDF = async () => {
    try {
      const pdf = new jsPDF("p", "mm", "a4");

      const pageWidth = pdf.internal.pageSize.getWidth();

      // ================= HEADER =================
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(18);
      pdf.setTextColor(46, 125, 50);
      pdf.text("fleetSync Analysis Report", 20, 20);

      pdf.setFontSize(10);
      pdf.setTextColor(100);
      pdf.text(`Date: ${new Date().toLocaleDateString()}`, 20, 28);

      // Right side brand name
      pdf.setFontSize(24);
      pdf.setTextColor(46, 125, 50);
      pdf.text("fleetSync", pageWidth - 20, 20, { align: "right" });

      // ================= METRICS BOX =================
      pdf.setDrawColor(200);
      pdf.rect(20, 40, 170, 35);

      pdf.setFontSize(12);
      pdf.setTextColor(0);

      pdf.text("Route Efficiency: 87%", 30, 55);
      pdf.text("Total Fleet: 42 Vehicles", 30, 65);
      pdf.text("Distance Covered: 12,540 km", 110, 55);
      pdf.text("CO₂ Emission: 2,540 kg", 110, 65);

      // ================= PIE CHART =================
      const pieCanvas = document.createElement("canvas");
      pieCanvas.width = 500;
      pieCanvas.height = 500;

      const pieChart = new Chart(pieCanvas.getContext("2d"), {
        type: "pie",
        data: {
          labels: ["Fuel Efficient", "Moderate", "High Emission"],
          datasets: [
            {
              data: [60, 25, 15],
              backgroundColor: ["#2E7D32", "#66BB6A", "#A5D6A7"],
            },
          ],
        },
        options: {
          animation: false,
          responsive: false,
        },
      });

      await new Promise((resolve) => setTimeout(resolve, 500));

      const pieImage = pieCanvas.toDataURL("image/jpeg", 1.0);
      pdf.text("Fleet Distribution", 20, 90);
      pdf.addImage(pieImage, "JPEG", 20, 95, 80, 80);

      pieChart.destroy();

      // ================= BAR CHART =================
      const barCanvas = document.createElement("canvas");
      barCanvas.width = 600;
      barCanvas.height = 400;

      const barChart = new Chart(barCanvas.getContext("2d"), {
        type: "bar",
        data: {
          labels: ["Jan", "Feb", "Mar", "Apr"],
          datasets: [
            {
              label: "CO₂ Emission",
              data: [400, 300, 500, 200],
              backgroundColor: "#2E7D32",
            },
          ],
        },
        options: {
          animation: false,
          responsive: false,
          plugins: {
            legend: { display: false },
          },
        },
      });

      await new Promise((resolve) => setTimeout(resolve, 500));

      const barImage = barCanvas.toDataURL("image/jpeg", 1.0);
      pdf.text("Monthly CO₂ Emission", 110, 90);
      pdf.addImage(barImage, "JPEG", 110, 95, 80, 80);

      barChart.destroy();

      // ================= FOOTER =================
      pdf.setFontSize(9);
      pdf.setTextColor(120);
      pdf.text("Generated by fleetSync System", 20, 285);

      pdf.save("fleetSync.pdf");
    } catch (error) {
      console.error("PDF generation failed:", error);
    }
  };

  return (
    <div style={{ padding: "40px" }}>
      <button
        onClick={generatePDF}
        style={{
          padding: "10px 20px",
          backgroundColor: "#2E7D32",
          color: "white",
          border: "none",
          borderRadius: "6px",
          cursor: "pointer",
        }}
      >
        Download Report
      </button>
    </div>
  );
}
